######################################################################
##
## Filename: ALUSrc1MUX.udo
## Created on: Fri Nov 25 15:45:53 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
