######################################################################
##
## Filename: cpu.udo
## Created on: Wed Nov 30 16:25:24 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
