######################################################################
##
## Filename: IF_IDRegs.udo
## Created on: Sat Nov 26 20:35:21 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
