######################################################################
##
## Filename: PC.udo
## Created on: Thu Nov 24 21:03:54 中国标准时间 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
